export const projectId = 'smrstakdtxiqrlnxibvz';
export const publicAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtcnN0YWtkdHhpcXJsbnhpYnZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxMTE0NzQsImV4cCI6MjA4NDY4NzQ3NH0.uTtVzpLAf6qvlYnAbAZPHJKayaqjTaD9HpmdO2iEORI';
